In [16]:
import numpy as np
import pandas as pd


df_data = pd.read_table('../arff/new_data.tsv')

In [17]:
df_data.head()

,Label,Chr,Position,RSID,Ref,Alt,Gene,GT,OMIM,CADD,...,MP_0004133,MP_0004134,MP_0005408,MP_0005451,MP_0005621,MP_0009389,MP_0010678,MP_0010769,MP_0012719,MP_0013328
0,CASE,7,4820844,rs397704705,GGAT,TGCTGTAAACTGTAACTGTAAA,AP5Z1,1/1,613647,29.5,...,0,0,0,0,0,0,0,0,0,0
1,CTRL,7,4833639,rs2880933,A,C,AP5Z1,1/1,613647,0.027,...,0,0,0,0,0,0,0,0,0,0
2,CASE,7,4827366,rs397704709,GGACCTGCCCTGCT,-,AP5Z1,1/1,613647,36.0,...,0,0,0,0,0,0,0,0,0,0
3,CTRL,7,4827366,rs397704709,GGACCTGCCCTGCT,-,AP5Z1,1/1,170500,36.0,...,0,0,0,0,0,0,0,0,0,0
4,CASE,11,126145284,rs267606829,C,T,FOXRED1,1/1,252010,27.7,...,0,0,0,1,1,0,0,0,0,0

In [18]:
df_data.replace('.', '?', inplace=True)

In [30]:
df_data.dtypes

Label                        int64
Chr                         object
Position                     int64
RSID                        object
Ref                         object
Alt                         object
Gene                        object
GT                           int64
OMIM                         int64
CADD                       float64
GWAVA                      float64
DANN                       float64
Similarity_score           float64
HP_0000078                   int64
HP_0000291                   int64
HP_0000708                   int64
HP_0001001                   int64
HP_0001939                   int64
HP_0002086                   int64
HP_0006476                   int64
HP_0009126                   int64
HP_0010515                   int64
HP_0010948                   int64
HP_0010987                   int64
HP_0011017                   int64
HP_0011025                   int64
HP_0011277                   int64
HP_0011482                   int64
HP_0011915                   int64
HP_0040063                   int64
                            ...
MP_0001983                   int64
MP_0002060                   int64
MP_0002089                   int64
MP_0002095                   int64
MP_0002106                   int64
MP_0002109                   int64
MP_0002138                   int64
MP_0002139                   int64
MP_0002163                   int64
MP_0002164                   int64
MP_0002396                   int64
MP_0003385                   int64
MP_0004133                   int64
MP_0004134                   int64
MP_0005408                   int64
MP_0005451                   int64
MP_0005621                   int64
MP_0009389                   int64
MP_0010678                   int64
MP_0010769                   int64
MP_0012719                   int64
MP_0013328                   int64
Inheritence_mode_0           uint8
Inheritence_mode_1           uint8
Inheritence_mode_2           uint8
Inheritence_mode_3           uint8
CADD_impute                  int64
GWAVA_impute                 int64
Similarity_score_impute      int64
DANN_impute                  int64
dtype: object

In [27]:
df_data['Label'].replace('CASE', 1, inplace = True)
df_data['Label'].replace('CTRL', 0, inplace = True)

df_data['GT'].replace('1/1', 1, inplace = True)
df_data['GT'].replace('0/1', 0, inplace = True)


df_data = pd.get_dummies(df_data, columns=['Inheritence_mode'])

In [29]:
df_data['CADD_impute'] = [1 if ele  == '?' else 0 for ele in df_data['CADD']]
df_data['GWAVA_impute'] = [1 if ele  == '?' else 0 for ele in df_data['GWAVA']]
df_data['Similarity_score_impute'] = [1 if ele  == '?' else 0 for ele in df_data['Similarity_score']]
df_data['DANN_impute'] = [1 if ele  == '?' else 0 for ele in df_data['DANN']]

df_data.replace('?', np.nan, inplace=True)


df_data['CADD'] = pd.to_numeric(df_data['CADD'], errors='coerce')
df_data['DANN'] = pd.to_numeric(df_data['DANN'], errors='coerce')
df_data['GWAVA'] = pd.to_numeric(df_data['GWAVA'], errors='coerce')
df_data['Similarity_score'] = pd.to_numeric(df_data['Similarity_score'], errors='coerce')

    
df_data.fillna(df_data.mean(), inplace = True)

,Label,Chr,Position,RSID,Ref,Alt,Gene,GT,OMIM,CADD,...,MP_0012719,MP_0013328,Inheritence_mode_0,Inheritence_mode_1,Inheritence_mode_2,Inheritence_mode_3,CADD_impute,GWAVA_impute,Similarity_score_impute,DANN_impute
0,1,7,4820844,rs397704705,GGAT,TGCTGTAAACTGTAACTGTAAA,AP5Z1,1,613647,29.500000,...,0,0,0,1,0,0,0,0,0,0
1,0,7,4833639,rs2880933,A,C,AP5Z1,1,613647,0.027000,...,0,0,0,1,0,0,0,0,0,0
2,1,7,4827366,rs397704709,GGACCTGCCCTGCT,-,AP5Z1,1,613647,36.000000,...,0,0,0,1,0,0,0,0,0,0
3,0,7,4827366,rs397704709,GGACCTGCCCTGCT,-,AP5Z1,1,170500,36.000000,...,0,0,1,0,0,0,0,0,0,0
4,1,11,126145284,rs267606829,C,T,FOXRED1,1,252010,27.700000,...,0,0,0,1,0,0,0,0,0,0
5,0,11,126142990,rs113976905,T,C,FOXRED1,1,252010,4.887000,...,0,0,0,1,0,0,0,0,0,0
6,1,11,126147412,rs267606830,A,G,FOXRED1,1,252010,26.000000,...,0,0,0,1,0,0,0,1,0,0
7,0,11,126147412,rs267606830,A,G,FOXRED1,1,610198,26.000000,...,0,0,0,1,0,0,0,1,0,0
8,1,6,26091306,rs28934596,T,C,HFE,1,235200,26.000000,...,0,1,0,1,0,0,0,0,0,0
9,0,6,26091306,rs28934596,T,C,HFE,1,300987,26.000000,...,0,0,0,0,0,1,0,0,1,0
10,1,6,26091269,rs28934597,G,C,HFE,1,235200,24.600000,...,0,1,0,1,0,0,0,0,0,0
11,0,6,26093236,rs1800758,G,A,HFE,1,235200,11.020000,...,0,1,0,1,0,0,0,0,0,0
12,1,6,26091582,rs28934595,A,C,HFE,1,235200,0.208000,...,0,1,0,1,0,0,0,0,0,0
13,0,6,26093236,rs1800758,G,A,HFE,0,235200,11.020000,...,0,1,0,1,0,0,0,0,0,0
14,1,6,26093443,rs111033558,G,T,HFE,1,235200,20.500000,...,0,1,0,1,0,0,0,0,0,0
15,0,6,26091149,rs28934889,G,A,HFE,0,235200,26.800000,...,0,1,0,1,0,0,0,0,0,0
16,1,6,26093144,rs111033563,A,C,HFE,1,235200,23.800000,...,0,1,0,1,0,0,0,0,0,0
17,0,6,26094433,rs35201683,C,T,HFE,0,235200,9.816000,...,0,1,0,1,0,0,0,0,0,0
18,1,2,20189045,rs397515534,T,C,WDR35,1,613610,25.600000,...,1,0,0,1,0,0,0,1,0,0
19,0,2,20135283,rs6741091,T,C,WDR35,0,613610,1.327000,...,1,0,0,1,0,0,0,0,0,0
20,1,2,20145548,rs267607174,T,C,WDR35,1,613610,29.600000,...,1,0,0,1,0,0,0,1,0,0
21,0,2,20145548,rs267607174,T,C,WDR35,1,115210,29.600000,...,0,0,1,0,0,0,0,1,0,0
22,1,2,20131136,rs397515334,G,-,WDR35,1,613610,24.178707,...,1,0,0,1,0,0,1,0,0,1
23,0,2,20135283,rs6741091,T,C,WDR35,1,613610,1.327000,...,1,0,0,1,0,0,0,0,0,0
24,1,2,20133230,rs267607175,C,T,WDR35,1,613610,34.000000,...,1,0,0,1,0,0,0,1,0,0
25,0,2,20133230,rs267607175,C,T,WDR35,1,613411,34.000000,...,0,0,0,1,0,0,0,1,0,0
26,1,20,25304045,rs387906217,TC,AAA,ABHD12,1,612674,32.000000,...,0,0,0,1,0,0,0,0,0,0
27,0,20,25281184,rs11100,G,C,ABHD12,0,612674,2.631000,...,0,0,0,1,0,0,0,0,0,0
28,1,7,128415610,rs104894031,C,T,OPN1SW,1,190900,23.300000,...,0,0,1,0,0,0,0,0,0,0
29,0,7,128415610,rs104894031,C,T,OPN1SW,1,609152,23.300000,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105502,1,9,130430467,rs886041978,G,A,STXBP1,0,612164,26.200000,...,0,0,1,0,0,0,0,1,0,0
105503,0,9,130430467,rs886041978,G,A,STXBP1,0,223000,26.200000,...,0,0,0,1,0,0,0,1,0,0
105504,1,22,17690423,rs199614299,G,A,CECR1,1,109650,23.000000,...,0,0,0,0,0,1,0,0,0,0
105505,0,22,17690423,rs199614299,G,A,CECR1,1,604432,23.000000,...,0,0,1,0,0,0,0,0,0,0
105506,1,22,17690423,rs199614299,G,A,CECR1,0,109650,23.000000,...,0,0,0,0,0,1,0,0,0,0
105507,0,22,17690423,rs199614299,G,A,CECR1,0,615185,23.000000,...,0,0,1,0,0,0,0,0,0,0
105508,1,22,17670877,rs146597836,C,T,CECR1,1,109650,2.643000,...,0,0,0,0,0,1,0,0,0,0
105509,0,22,17670877,rs146597836,C,T,CECR1,1,600496,2.643000,...,0,0,1,0,0,0,0,0,0,0
105510,1,22,17670877,rs146597836,C,T,CECR1,0,109650,2.643000,...,0,0,0,0,0,1,0,0,0,0
105511,0,22,17670877,rs146597836,C,T,CECR1,0,103285,2.643000,...,0,0,1,0,0,0,0,0,0,0
105512,1,22,17684466,rs750868279,G,A,CECR1,1,109650,16.470000,...,0,0,0,0,0,1,0,0,0,0
105513,0,22,17684466,rs750868279,G,A,CECR1,1,610370,16.470000,...,0,0,0,1,0,0,0,0,0,0
105514,1,22,17684466,rs750868279,G,A,CECR1,0,109650,16.470000,...,0,0,0,0,0,1,0,0,0,0
105515,0,22,17684466,rs750868279,G,A,CECR1,0,607596,16.470000,...,0,0,0,1,0,0,0,0,0,0
105516,1,16,3299480,rs755659290,T,C,MEFV,1,109650,23.300000,...,0,0,0,0,0,1,0,0,0,0
105517,0,16,3299480,rs755659290,T,C,MEFV,1,300400,23.300000,...,0,1,0,0,0,1,0,0,0,0
105518,1,16,3299480,rs755659290,T,C,MEFV,0,109650,23.300000,...,0,0,0,0,0,1,0,0,0,0
105519,0,16,3299480,rs755659290,T,C,MEFV,0,616801,23.300000,...,0,0,0,0,0,1,0,0,1,0
105520,1,18,50866145,rs199651452,A,T,DCC,1,217990,21.800000,...,0,0,0,1,0,0,0,0,0,0
105521,0,18,50866145,rs199651452,A,T,DCC,1,235200,21.800000,...,0,1,0,1,0,0,0,0,0,0
105522,1,18,50866178,rs775565634,G,A,DCC,1,217990,24.200000,...,0,0,0,1,0,0,0,0,0,0
105523,0,18,50866178,rs775565634,G,A,DCC,1,610006,24.200000,...,0,0,0,1,0,0,0,0,0,0
105524,1,19,17081703,rs756064750,G,GG,CPAMD8,1,617319,21.700000,...,0,0,0,0,0,1,0,0,1,0
105525,0,19,17081703,rs756064750,G,GG,CPAMD8,1,606159,21.700000,...,0,0,1,0,0,0,0,0,1,0
105526,1,19,17081703,rs756064750,G,GG,CPAMD8,0,617319,21.700000,...,0,0,0,0,0,1,0,0,1,0
105527,0,19,17081703,rs756064750,G,GG,CPAMD8,0,190440,21.700000,...,0,0,1,0,0,0,0,0,1,0
105528,1,19,17014434,rs369858688,C,T,CPAMD8,1,617319,24.600000,...,0,0,0,0,0,1,0,0,1,0
105529,0,19,17014434,rs369858688,C,T,CPAMD8,1,614436,24.600000,...,0,0,1,0,0,0,0,0,1,0
105530,1,19,17014434,rs369858688,C,T,CPAMD8,0,617319,24.600000,...,0,0,0,0,0,1,0,0,1,0
105531,0,19,17014434,rs369858688,C,T,CPAMD8,0,156500,24.600000,...,0,0,1,0,0,0,0,0,1,0

In [31]:
df_data.to_csv('PVP_new_data.csv', index = None)

### --End--